repos:
  - repo: local
    hooks:
      - id: commit-message-prefix
        name: Commit Message Prefix Check
        entry: bash .github/hooks/commitMsg.sh
        language: system
        stages: [commit-msg]

      - id: branch-name-prefix
        name: Branch Name Prefix Check
        entry: bash .github/hooks/branchName.sh
        language: system
        stages: [pre-commit]
        always_run: true
      
      - id: formatting
        name: Code Formatting
        entry: bash -c "STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp|c|h)$'); if [ -n \"$STAGED_FILES\" ]; then echo \"$STAGED_FILES\" | xargs clang-format -i; echo \"$STAGED_FILES\" | xargs git add; fi"
        language: system
        stages: [pre-commit]
        always_run: true
      
