repos:
  - repo: local
    hooks:
      - id: commit-message-prefix
        name: Commit Message Prefix Check
        entry: bash .github/hooks/commitMsg.sh
        language: system
        stages: [commit-msg]

      - id: branch-name-prefix
        name: Branch Name Prefix Check
        entry: bash .github/hooks/branchName.sh
        language: system
        stages: [pre-commit]
        always_run: true
      
      - id: formatting
        name: Code Formatting
        entry: bash -c "TEMP_FILE=$(mktemp); git diff --cached --name-only > \"$TEMP_FILE\"; make format; cat \"$TEMP_FILE\" | xargs git add; rm \"$TEMP_FILE\""
        language: system
        stages: [pre-commit]
        always_run: true
      
