logger::ALogger
LogLevel logger::ALogger::m_currentLogLevel
Referenced by getLevel, logger::ConsoleLogger::log, logger::FileLogger::log, operator=, setLevel.
logger::ALogger::ALogger()
Constructs a new ALogger object with the default log level set to INFO.
Initializes the ALogger object with a default log level of DEBUG.
logger::ALogger::ALogger(const ALogger &other)
Copy constructor.
Creates a new ALogger object as a copy of an existing one. other The ALogger object to copy from.
LogLevel logger::ALogger::getLevel() const
Returns the current log level.
Retrieves the current log level of the logger. The current log level.
References m_currentLogLevel.
virtual void logger::ALogger::log(const std::string &message, LogLevel level)=0
ALogger & logger::ALogger::operator=(const ALogger &other)
Copy assignment operator.
Assigns the state of another ALogger object to this one. other The ALogger object to assign from. A reference to this ALogger object.
References m_currentLogLevel.
Referenced by logger::ConsoleLogger::operator=, logger::FileLogger::operator=.
void logger::ALogger::setLevel(LogLevel level)
Sets the current log level.
Updates the log level of the logger. Only messages with a level less than or equal to this new level will be logged. level The new log level to set.
References m_currentLogLevel.
logger::ALogger::~ALogger()
Destroys the ALogger object.
Cleans up resources used by the ALogger object. This is a virtual destructor to ensure proper cleanup in derived classes.
std::string logger::ALogger::getLogPrefix(LogLevel level)
Creates Prefix for Logs.
This method calls getLogLevelAsString and getTimeStamp to create the log msg Prefix. Example output: "[DEBUG] [2024-09-11 14:30:45]" std::string representing the prefix for the log msg. std::runtime_error If the conversion of the time to local time fails.
References getLogLevelAsString, getTimeStamp.
Referenced by logger::ConsoleLogger::log, logger::FileLogger::log.
std::string logger::ALogger::getLogLevelAsString(LogLevel level)
Converts a log level to its string representation.
Converts the specified log level to a readable string, such as "[INFO]" or "[ERROR]". level The log level to convert. A string representing the provided log level.
References logger::DEBUG, logger::DEBUG_COLOR, logger::ERROR, logger::ERROR_COLOR, logger::FATAL, logger::FATAL_COLOR, logger::INFO, logger::INFO_COLOR, logger::RESET, logger::WARNING, logger::WARNING_COLOR.
Referenced by getLogPrefix.
std::string logger::ALogger::getTimeStamp()
Retrieves the current timestamp in a formatted string.
This method obtains the current local time and formats it as a string in the format "YYYY-MM-DD HH:MM:SS". The timestamp is enclosed in square brackets. Example output: "[2024-09-11 14:30:45]" std::string A string representing the current timestamp. std::runtime_error If the conversion of the time to local time fails.
Referenced by getLogPrefix.