logger::LoggerManager
typedef std::map<std::string, ALogger*> logger::LoggerManager::LogMap
LogLevel logger::LoggerManager::m_globalLogLevel
Referenced by getGlobalLogLevel, log, operator=, setGlobalLogLevel.
LogMap logger::LoggerManager::m_loggers
Referenced by log, registerLogger, setLoggerLevel, unregisterLogger.
LoggerManager & logger::LoggerManager::getInstance()
Provides access to the singleton instance of LoggerManager.
This method ensures that only one instance of LoggerManager exists and provides access to it. The instance is created on first use and is returned for all subsequent calls. A reference to the singleton LoggerManager instance.
Referenced by main.
LogLevel logger::LoggerManager::getGlobalLogLevel() const
Gets the current global log level.
Retrieves the global log level, which determines the minimum level of messages that will be processed by the manager. The current global log level.
References m_globalLogLevel.
void logger::LoggerManager::log(const std::string &message, LogLevel level)
Logs a message to all registered loggers.
Sends a log message to all loggers that have been registered with the manager, provided that the global log level allows for the message to be logged. message The message to log. level The log level of the message.
References m_globalLogLevel, m_loggers.
void logger::LoggerManager::registerLogger(const std::string &loggerName, ALogger *logger)
Registers a new logger with the manager.
Adds a logger to the manager's collection, associating it with a specified name. If a logger with the same name already exists, it will be replaced. loggerName The name to associate with the logger. logger A shared pointer to the ALogger object to register.
References m_loggers.
Referenced by main.
void logger::LoggerManager::setGlobalLogLevel(LogLevel level)
Sets the global log level.
Changes the global log level. Only messages with a log level equal to or higher than the new global level will be processed by the manager. level The new global log level.
References m_globalLogLevel.
Referenced by main.
void logger::LoggerManager::setLoggerLevel(const std::string &loggerName, LogLevel level)
Sets the log level for a specific logger.
Changes the logging level of a specific logger by its name. Only messages with a log level equal to or higher than the new level will be logged by that logger. loggerName The name of the logger whose level to set. level The new log level for the specified logger. std::out_of_range If the logger with the specified name is not found.
References m_loggers.
Referenced by main.
void logger::LoggerManager::unregisterLogger(const std::string &loggerName)
Unregisters a logger from the manager.
Removes the logger associated with the given name from the manager's collection. If no logger with the specified name exists, this operation has no effect. loggerName The name of the logger to unregister.
References m_loggers.
Referenced by main.
logger::LoggerManager::LoggerManager()
Constructs a new LoggerManager object.
Initializes the LoggerManager object with a default global log level of INFO.
logger::LoggerManager::LoggerManager(const LoggerManager &)
LoggerManager & logger::LoggerManager::operator=(const LoggerManager &other)
Copy assignment operator.
Assigns the state of another LoggerManager object to this one. This operator allows copying of LoggerManager objects, but as LoggerManager does not have additional data members beyond those inherited from ALogger, the assignment is trivial. other The LoggerManager object to assign from. A reference to this LoggerManager object.
References m_globalLogLevel.
logger::LoggerManager::~LoggerManager()