name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  code-analysis-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t img .

      - name: Run strict checks
        run: |
          docker run --rm img make strict

  code-analysis-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build
        run: |
          make