name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed
      
jobs:
  delete_merged_branch:
    if: ${{ github.event.pull_request.merged }}  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete branch after merge
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}

          # Ensure branch is not the default branch
          if [ "$BRANCH_NAME" != "$DEFAULT_BRANCH" ]; then
            git push origin --delete "$BRANCH_NAME"
            echo "Deleted branch: $BRANCH_NAME"
          else
            echo "Cannot delete the default branch: $BRANCH_NAME"
          fi
