name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to Docs Branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan docs
          git --work-tree ./docs_output/html add --all
          git commit -m "Deploy updated Doxygen documentation"
          git push -f origin docs
