name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
      - chore/docs
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Install Graphviz
        run: |
          sudo apt-get install -y graphviz

      - name: Download awesome-doxygen
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css.git
          cp doxygen-awesome-css/doxygen-awesome.css docs/

      - name: Generate Doxygen documentation
        run: |
          cd docs && doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: .
