name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to Docs Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'Jakobus42'
          git config --global user.email 'Jakob.sadjina@icloud.com'
          git checkout --orphan docs
          git rm -rf .
          cp -r ./docs_output/html/* .
          git add --all
          git commit -m "Deploy updated Doxygen documentation" --no-verify
          git push -f https://x-access-token:$GITHUB_TOKEN@github.com/Jakobus42/webserv.git docs
          