name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Download Doxygen Awesome CSS
        run: curl -o doxygen-awesome.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to Docs Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Jakobus42'
          git config --global user.email 'Jakob.sadjina@icloud.com'
          git checkout --orphan docs
          git rm -rf .
          cp -r ./docs_output/html/* .
          git add .
          git commit -m "Deploy updated Doxygen documentation" --no-verify
          git push -f https://x-access-token:$GITHUB_TOKEN@github.com/Jakobus42/webserv.git docs
